{
 "title": "Job - RMS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "jobid",
    "label": "Job ID",
    "query": {
     "query": "label_values(rmsjob_info,jobid)"
    }
   },
   { "name": "interval", "label": "Resolution", "query": "0.1s,0.5s,1s,5s,15s,30s,60s" },
   { "name": "node_exporter_port", "query": "9100" },
   {
    "name": "counters",
    "label": "Counters",
    "query": {
     "query": "query_result(group by (counter) (omnistat_rocprofiler * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"})))"
    }
   },
   {
    "name": "figures",
    "label": "Figures of merit",
    "query": {
     "query": "query_result(group by (name) (omnistat_fom * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"})))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Job Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$jobid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "{{batchflag}}"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rmsjob_info{jobid=\"$jobid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rocm_num_gpus * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "max(timestamp(rmsjob_info{jobid=\"$jobid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GPU",
   "type": "stat",
   "description": "Average over time of the average GPU Utilization of all GPUs.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all GPUs in all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "stat",
   "description": "Average over time of the average of GPU Memory utilization of all GPUs.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all GPUs in all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max(rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "stat",
   "description": "Average over time of the average 1m Load Average of all nodes.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_load1 * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(node_load1 * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "CPU Memory",
   "type": "stat",
   "description": "Average over time of the average memory utilization of all nodes.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(100 * ((node_memory_MemTotal_bytes  -node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 * ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "stat",
   "description": "Aggregate network bandwidth of all nodes. Includes received and transmitted data.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))) + sum(rate(node_network_transmit_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Ethernet"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))) + sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Infiniband"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Average of all nodes.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$__rate_interval]) * on (instance) group_left()(label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Eth Rx"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[$__rate_interval]) * on (instance) group_left()(label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "Eth Tx"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "IB Rx"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval]) * on (instance) group_left() (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\")))",
     "legendFormat": "IB Tx"
    }
   ]
  },
  {
   "title": "GPU Usage [aggregated by node]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 507 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per Node",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 515 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Utilization per Node",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 515 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage [aggregated by GPU ID]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean GPU Utilization (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 31 },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "Max GPU Memory Utilization (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 417 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 417 },
     "targets": [
      {
       "expr": "avg by (card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 425 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage [all GPUs]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_vram_used_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "Distribution of Average Utilization per GPU",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Utilization per GPU",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Distribution of GPU Utilization Over Time (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "quantile(0.20, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.2 "
      },
      {
       "expr": "quantile(0.5, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Median"
      },
      {
       "expr": "quantile(0.8, (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) ",
       "legendFormat": "Quantile 0.8"
      },
      {
       "expr": "avg(rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Telemetry [aggregated by node]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance, location) (rocm_temperature_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{location}}"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 238 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance, location) (rocm_temperature_memory_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{location}}"
      }
     ]
    },
    {
     "title": "GPU Power (W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_average_socket_power_watts * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Engine Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_sclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Memory Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance) (rocm_mclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Telemetry [aggregated by GPU ID]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 444 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (card, location) (rocm_temperature_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}} ({{location}})"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (card, location) (rocm_temperature_memory_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}} ({{location}})"
      }
     ]
    },
    {
     "title": "GPU Power (W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 460 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_average_socket_power_watts * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Engine Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 468 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_sclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Memory Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 468 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (card) (rocm_mclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "GPU ID {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Telemetry [all GPUs]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 344 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance,card) (rocm_utilization_percentage * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 352 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance, card, location) (rocm_temperature_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}, {{location}}"
      }
     ]
    },
    {
     "title": "GPU Memory Temperature (°C)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 360 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg by (instance, card, location) (rocm_temperature_memory_celsius * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}, {{location}}"
      }
     ]
    },
    {
     "title": "GPU Power (W)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 368 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (instance, card) (rocm_average_socket_power_watts * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Engine Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance, card) (rocm_sclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPU Frequency - Memory Clock (MHz)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "avg by (instance, card) (rocm_mclk_clock_mhz * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Occupancy [all GPUs]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU CU Occupancy (%)",
     "type": "timeseries",
     "description": "Estimated CU occupancy based on the number of in-flight waves of all processes running in each GPU. In-flight waves are translated into number of occupied compute units based on the maximum number of waves per CU. This estimate doesn't account for how waves are distributed, and is not always a good measure of performance.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3428 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rocm_compute_unit_occupancy * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"}) * 100 / (rocm_num_compute_units * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Counters [all GPUs]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Performance Counter $counters (counts/s)",
     "type": "timeseries",
     "description": "Performance counter rate using based on raw values from each counter without any other transformation.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2667 },
     "repeat": "counters",
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(omnistat_rocprofiler{counter=\"$counters\"}[$__rate_interval]) * on (instance) group_left() (rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Reliability, Availability, and Serviceability (RAS) [all GPUs]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPUs with Non-zero Rate of Correctable Errors (errors/min)",
     "type": "timeseries",
     "description": "Only showing GPUs and blocks with errors. A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3388 },
     "targets": [
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_umc_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "UMC, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_sdma_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "SDMA, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_gfx_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "GFX, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_mmhub_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "MMHUB, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_pcie_bif_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "PCIE BIF, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_hdp_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "HDP, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_xgmi_wafl_correctable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "XGMI WAFL, {{instance}}, {{card}}"
      }
     ]
    },
    {
     "title": "GPUs with Non-zero Rate of Uncorrectable Errors (errors/min)",
     "type": "timeseries",
     "description": "Only showing GPUs and blocks with errors. A panel with \"No data\" indicates no errors have been reported during the selected time window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3388 },
     "targets": [
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_umc_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "UMC, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_sdma_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "SDMA, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_gfx_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "GFX, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_mmhub_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "MMHUB, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_pcie_bif_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "PCIE BIF, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_hdp_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "HDP, {{instance}}, {{card}}"
      },
      {
       "expr": "sum by (instance,card) (delta(rocm_ras_xgmi_wafl_uncorrectable_count[1m] * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})) > 0",
       "legendFormat": "XGMI WAFL, {{instance}}, {{card}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - 1m Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3575 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(node_load1) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Main Memory - Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3575 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * ((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth - Ethernet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet Bandwidth - Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6247 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ethernet Bandwidth - Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6247 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Bandwidth - High Performance Interconnect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infiniband Bandwidth - Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7395 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Infiniband Bandwidth - Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7395 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO - Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18169 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_read_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IO - Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18169 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_disk_written_bytes_total[$__rate_interval])) * on (instance) (label_replace(rmsjob_info{jobid=\"$jobid\"}, \"instance\", \"$1:$node_exporter_port\", \"instance\", \"(.*):(.*)\"))\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Figures of Merit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Figure of Merit $figures",
     "type": "timeseries",
     "description": "User-provided figure of merit.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2673 },
     "repeat": "figures",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(omnistat_fom{name=\"$figures\"} * on (instance) group_left() rmsjob_info{jobid=\"$jobid\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Annotated Regions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2722 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(count by (marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (marker) (avg by (instance) (rocm_utilization_percentage) * on (instance) group_left(jobid,marker) rmsjob_info{jobid=\"$jobid\"} * on (jobid) group_left(marker) count by (jobid,marker) (rmsjob_annotations{jobid=\"$jobid\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Steps - Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Steps",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16723 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))*1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Elapsed Time",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16723 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 107 }
     ]
    },
    {
     "title": "GPU Utilization per Job Step",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16731 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "avg by (jobstep) ((rocm_utilization_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobstep) ((rocm_utilization_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16731 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 108 }
     ]
    },
    {
     "title": "GPU Memory Utilization per Job Step",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16739 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "avg by (jobstep) ((rocm_vram_used_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobstep) ((rocm_vram_used_percentage) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16739 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 109 }
     ]
    },
    {
     "title": "GPU Power per Job Step",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16747 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "avg by (jobstep) ((rocm_average_socket_power_watts) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (jobstep) ((rocm_average_socket_power_watts) * on (instance) group_left(jobid,jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      },
      {
       "expr": "timestamp(count by (jobstep) (rmsjob_info{jobid=\"$jobid\",jobstep!=\"-1\"} > 0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average GPU Power",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16747 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      { "panelId": 110 }
     ]
    }
   ]
  }
 ]
}